MEDAL_HEADER_MAP_ASIA = {
    "MEDAL OF EXCELLENCE": "Exzellenz Kampfkruiz",
    "MEDAL OF VALOR": "Heldenmut Verdienstmedaille",
    "MEDAL OF BRAVERY": "Tapferkeit Verdienstmedaille",
    "CHAPLAIN'S MEDAL": "Kaplan Verdienstkruiz",
    "FLAG-BEARER CROSS": "Fähnrich Kampfkruiz",
    "FLAG-GUARD MEDAL": "Fahnenfeldweibel Verdienstmedaille",
    "SOCIAL MEDAL": "Gesellschafts Verdienstmedaille",
    "RECRUITER'S MEDAL": "Rekrutierungs Verdienstmedaille",
    "ARTIST'S MEDAL": "Künstler Verdienstmedaille",
    "ARTILLERY KORPS MEDAL": "Artillerie Korps Verdienstmedaille",
    "VIERTES KORPS MEDAL": "Viertes Korps Verdienststern",
    "GRENADIER KORPS MEDAL": "Grenadier Korps Ehrenkruiz",
    "HUNGARIAN KORPS MEDAL": "Ungarische Korps Verdienstmedaille",
}
